// <auto-generated />
namespace Mepham.Forum.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TopicBasicImplementation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TopicBasicImplementation));
        
        string IMigrationMetadata.Id
        {
            get { return "201610191530351_TopicBasicImplementation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
