// <auto-generated />
namespace Mepham.Forum.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestingDefaultValueAttribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestingDefaultValueAttribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201610191324356_TestingDefaultValueAttribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
